/*
 * FenetrePopup.java
 *
 * Created on 25 mai 2008
 * By Yann39 <rockyracer@mailfence.com>
 */

package projetlangageformel;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author  Yann
 */
public class FenetrePopup extends javax.swing.JFrame {
       
    public static JScrollPane jScrollPane1;
    public static JPanel jPanel1;
    
    /** Creates new form FenetrePopup */
    public FenetrePopup() {
        initComponents();
    }
        
    public static void showOnFrame(JComponent component, String frameName, int largeur, int hauteur) {
        //cr�ation de la fen�tre
        JFrame frame = new JFrame(frameName);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
        
        //cr�ation du JScrollPane contenant la pyramide 
        jScrollPane1 = new JScrollPane(component);
        //On r�gle l'apparition des scrollbar que si la pyramide d�passe 1024x768 pixels
        if (largeur < 1024 && hauteur < 768)
            jScrollPane1.setPreferredSize(new Dimension(largeur+10,hauteur+10));
        else if (largeur >= 1024 && hauteur < 768)
            jScrollPane1.setPreferredSize(new Dimension(1024,hauteur+10));
        else if (largeur < 1024 && hauteur >= 768)
            jScrollPane1.setPreferredSize(new Dimension(largeur+10,768));
        else
            jScrollPane1.setPreferredSize(new Dimension(1024,768));
        jScrollPane1.setWheelScrollingEnabled(true);
        //cr�ation du JPanel contenant le JScrollPane
        jPanel1 = new JPanel();
        jPanel1.setSize(largeur+10,hauteur+10);
        jPanel1.add(jScrollPane1);
        //ajout du JPanel � la fen�tre
        frame.getContentPane().add("West",jPanel1);
        frame.pack();
        //Centre la fen�tre au milieu de l'�cran
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((screen.width/2) - (frame.getSize().width/2),((screen.height/2) - (frame.getSize().height/2)));
        frame.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePopup().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
