/*
 * JCanvas.java
 *
 * Created on 22 mai 2008
 * By Yann39 <rockyracer@mailfence.com>
 */

package projetlangageformel;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

public class JCanvas extends javax.swing.JPanel {
   
    protected String[][] pyramide;
    protected int nbFeuilles;
    protected int taillePlusGrandTerme;
    protected String[][] couples;
    protected String nom;
    
    public JCanvas(String[][] pyr, int nbFeu, int taillePGTerme, String[][] cpl, String name) {
        initComponents();
        this.pyramide = pyr;
        this.nbFeuilles = nbFeu;
        this.taillePlusGrandTerme = taillePGTerme;
        this.couples = cpl;
        this.nom = name;
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        int largeurCases=0;
        if (taillePlusGrandTerme==1) {
            largeurCases = 24;
        }
        else
            largeurCases = 12*taillePlusGrandTerme;
        int hauteurCases = 16;
        int decalageHoriz = ((nbFeuilles*largeurCases)+((nbFeuilles-1)*4))/2;
        int decalageVerti = 10;
        int positionHoriz = 0;
        for(int i=0; i<nbFeuilles; i++) {
            for(int j=0; j<=i; j++) {
                if (nom == "Pyramide") {
                    g.drawRect(decalageHoriz+positionHoriz,decalageVerti,largeurCases,hauteurCases);
                    g.drawString(pyramide[i][j]+"",decalageHoriz+positionHoriz+4,decalageVerti+13);
                }
                else {
                    Color rouge = new Color(255,0,0);
                    Color noir = new Color(0,0,0);
                    if (pyramide[i][j]=="")
                        g.drawRect(decalageHoriz+positionHoriz,decalageVerti,largeurCases,hauteurCases);
                    else {
                        g.setColor(rouge);
                        g.drawRect(decalageHoriz+positionHoriz,decalageVerti,largeurCases,hauteurCases);
                        g.setColor(noir);
                    }
                    g.drawString(pyramide[i][j]+"",decalageHoriz+positionHoriz+4,decalageVerti+13);
                    g.setFont(new Font("sansserif", Font.PLAIN, 8));
                    g.setColor(rouge);
                    g.drawString(couples[i][j]+"",decalageHoriz+positionHoriz+14,decalageVerti+9);
                    g.setColor(noir);
                    g.setFont(new Font("sansserif", Font.PLAIN, 12));
                }
                positionHoriz=positionHoriz+largeurCases+4;
            }
            decalageHoriz=decalageHoriz-((largeurCases+4)/2);
            decalageVerti=decalageVerti+20;
            positionHoriz=0;
        }
         
        return;
    }

    public void update(Graphics g){
        paintComponent(g);
        return;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
